export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  DASHBOARD_APPOINTMENTS: '/dashboard/appointments',
  DASHBOARD_CLIENTS: '/dashboard/clients',
  DASHBOARD_CLIENT_DETAIL: '/dashboard/clients/:id',
  DASHBOARD_SERVICES: '/dashboard/services',
  DASHBOARD_FACIAL_ANALYSIS: '/dashboard/facial-analysis',
  DASHBOARD_PAYMENTS: '/dashboard/payments',
  DASHBOARD_REVIEWS: '/dashboard/reviews',
  DASHBOARD_REPORTS: '/dashboard/reports',
  DASHBOARD_SETTINGS: '/dashboard/settings',
  DASHBOARD_SCHEDULER: '/dashboard/scheduler',
  DASHBOARD_SCHEDULES: '/dashboard/schedules',
  DASHBOARD_USERS: '/dashboard/users',
  DASHBOARD_SESSIONS: '/dashboard/sessions',
  DASHBOARD_NOTIFICATIONS: '/dashboard/notifications',
  DASHBOARD_AUDIT_LOGS: '/dashboard/audit-logs',
};